name: Custom - Acceptance Tests

on:
  workflow_run:
    workflows: ["Unattended - Docker Build"]
    branches: [master]
    types: [completed]

jobs:
  acceptance_tests:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: LouisBrunner/checks-action@v1.1.1
        name: Check Runs Initialization
        id: check_init
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Acceptance Tests
          status: in_progress
          sha: ${{ github.event.workflow_run.head_sha }}
      - run: echo "Custom - Acceptance Tests"
        id: test
      - uses: LouisBrunner/checks-action@v1.1.1
        name: Check Runs Completion
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          check_id: ${{ steps.check_init.outputs.check_id }}
          status: completed
          output: |
            {"summary":"Check Run set to Done"}
          conclusion: ${{ steps.test.conclusion }}
